#!/bin/sh
grep 'http://dbpedia.org/ontology/birthPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_birthPlace.csv
grep 'http://dbpedia.org/ontology/country' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_country.csv
grep 'http://dbpedia.org/ontology/date' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_date.csv
grep 'http://dbpedia.org/ontology/deathCause' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_deathCause.csv
grep 'http://dbpedia.org/ontology/deathDate' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_deathDate.csv
grep 'http://dbpedia.org/ontology/deathPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_deathPlace.csv
grep 'http://dbpedia.org/ontology/dissolutionDate' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_dissolutionDate.csv
grep 'http://dbpedia.org/ontology/foundationPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_foundationPlace.csv
grep 'http://dbpedia.org/ontology/inflow' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_inflow.csv
grep 'http://dbpedia.org/ontology/knownFor' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_knownFor.csv
grep 'http://dbpedia.org/ontology/locatedInArea' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_locatedInArea.csv
grep 'http://dbpedia.org/ontology/operator' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_operator.csv
grep 'http://dbpedia.org/ontology/populationTotal' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_populationTotal.csv
grep 'http://dbpedia.org/ontology/residence' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_residence.csv
grep 'http://dbpedia.org/ontology/routeEnd' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_routeEnd.csv
grep 'http://dbpedia.org/ontology/routeStart' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_routeStart.csv
grep 'http://dbpedia.org/ontology/seatingCapacity' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_seatingCapacity.csv
grep 'http://dbpedia.org/ontology/wineProduced' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_wineProduced.csv
grep 'http://dbpedia.org/property/location' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbp_location.csv
