#!/bin/sh
grep 'http://dbpedia.org/ontology/birthPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_birthPlace.csv
grep 'http://dbpedia.org/ontology/birthYear' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_birthYear.csv
grep 'http://dbpedia.org/ontology/budget' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_budget.csv
grep 'http://dbpedia.org/ontology/capital' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_capital.csv
grep 'http://dbpedia.org/ontology/child' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_child.csv
grep 'http://dbpedia.org/ontology/coach' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_coach.csv
grep 'http://dbpedia.org/ontology/composer' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_composer.csv
grep 'http://dbpedia.org/ontology/connotation' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_connotation.csv
grep 'http://dbpedia.org/ontology/currency' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_currency.csv
grep 'http://dbpedia.org/ontology/deathPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_deathPlace.csv
grep 'http://dbpedia.org/ontology/dissolutionDate' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_dissolutionDate.csv
grep 'http://dbpedia.org/ontology/elevation' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_elevation.csv
grep 'http://dbpedia.org/ontology/firstAscentPerson' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_firstAscentPerson.csv
grep 'http://dbpedia.org/ontology/foundedBy' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_foundedBy.csv
grep 'http://dbpedia.org/ontology/founder' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_founder.csv
grep 'http://dbpedia.org/ontology/governmentType' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_governmentType.csv
grep 'http://dbpedia.org/ontology/ground' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_ground.csv
grep 'http://dbpedia.org/ontology/influenced' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_influenced.csv
grep 'http://dbpedia.org/ontology/ingredient' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_ingredient.csv
grep 'http://dbpedia.org/ontology/leader' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_leader.csv
grep 'http://dbpedia.org/ontology/leaderName' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_leaderName.csv
grep 'http://dbpedia.org/ontology/literaryGenre' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_literaryGenre.csv
grep 'http://dbpedia.org/ontology/locatedInArea' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_locatedInArea.csv
grep 'http://dbpedia.org/ontology/location' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_location.csv
grep 'http://dbpedia.org/ontology/movement' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_movement.csv
grep 'http://dbpedia.org/ontology/nationality' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_nationality.csv
grep 'http://dbpedia.org/ontology/numberOfLocations' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_numberOfLocations.csv
grep 'http://dbpedia.org/ontology/numberOfPages' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_numberOfPages.csv
grep 'http://dbpedia.org/ontology/party' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_party.csv
grep 'http://dbpedia.org/ontology/populationTotal' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_populationTotal.csv
grep 'http://dbpedia.org/ontology/producer' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_producer.csv
grep 'http://dbpedia.org/ontology/programmingLanguage' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_programmingLanguage.csv
grep 'http://dbpedia.org/ontology/publisher' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_publisher.csv
grep 'http://dbpedia.org/ontology/residence' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_residence.csv
grep 'http://dbpedia.org/ontology/restingPlace' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_restingPlace.csv
grep 'http://dbpedia.org/ontology/series' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_series.csv
grep 'http://dbpedia.org/ontology/spouse' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_spouse.csv
grep 'http://dbpedia.org/ontology/vicePresident' ../resources/qald-lex/rules-predict_l_for_s_given_p-*.csv>>../resources/qald-lex/raw-dbo_vicePresident.csv
